name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Каждые 10 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cnuf4d6l6c7s63de5la0?key=UHgNK36oH9o"

